name: ai_mood_companion
description: AI chat companion with mood tracking, 3D-like UI, voice I/O. Codemagic-ready.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  intl: ^0.19.0
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  fl_chart: ^0.69.0
  confetti: ^0.7.0
  flutter_animate: ^4.5.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
